build: off

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

  matrix:
  - ARGS: ""
  #- ARGS: "--resolver lts-2"
  #- ARGS: "--resolver lts-3"
  #- ARGS: "--resolver lts-6"
  #- ARGS: "--resolver lts-7"
  # - ARGS: "--resolver lts-9"
  # - ARGS: "--resolver lts-11"
  # - ARGS: "--resolver lts-12"
  # - ARGS: "--resolver lts-13"
  # - ARGS: "--resolver lts-14"
  # - ARGS: "--resolver lts-15"
  - ARGS: "--resolver lts-16.23"
  #- ARGS: "--resolver nightly"

artifacts:
  - path: hsrl.zip
    name: hsrl

before_build:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

build_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul
- stack exec --no-terminal -- pacman -Syu --noconfirm > nul
- stack exec --no-terminal -- pacman -S   --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_ttf
- pkg-config --libs sdl2 --libs SDL2_ttf

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal build

- stack --local-bin-path . install hsrl
- 7z a hsrl.zip hsrl.exe "C:\Program Files\Git\mingw64\bin\SDL2.dll" "C:\Program Files\Git\mingw64\bin\SDL2_ttf.dll"
