build: off

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

  matrix:
  - ARGS: ""

artifacts:
  - path: hsrl.zip
    name: hsrl

before_build:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

build_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul
- stack exec --no-terminal -- pacman -Syu --noconfirm > nul
- stack exec --no-terminal -- pacman -S   --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2
- stack exec -- pkg-config --libs sdl2

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal build

- stack --local-bin-path . install hsrl
- 7z a -tzip hsrl.zip hsrl.exe res LICENSE
- forfiles /p C:\Users\appveyor\AppData\Local\Programs\stack\x86_64-windows /s /m "SDL*.dll" /c "cmd /c 7z.exe a -tzip C:\stack\hsrl.zip @file"
